### ISSUE TITLE
Using the WebAPIFactory throws an exception on auth server start

### ISSUE THREAD

**Issue by Herbstein** [peacecwz/spotify-api-netcore#1]
The following fails with a `System.ComponentModel.Win32Exception: No such file or directory` exception during auth server startup, specifically on [line 54](https://github.com/peacecwz/spotify-api-netcore/blob/master/src/Spotify.API.NetCore/Auth/ImplicitGrantAuth.cs#L54).
```csharp
new WebAPIFactory("<local_ip>", 8240, "<client_id>", scope.UserReadPlaybackState).GetWebApi().Result;
```

The full exception:

```
Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Spotify.API.NetCore.Auth.WebAPIFactory.GetWebApi(Boolean showDialog)
   at lyricsyfi.Api.Init() in /home/rasmus/dev/cs/lyricsyfi/lyricsyfi/Api.cs:line 19
   at lyricsyfi.Api..ctor() in /home/rasmus/dev/cs/lyricsyfi/lyricsyfi/Api.cs:line 13
   at lyricsyfi.Program.Main(String[] args) in /home/rasmus/dev/cs/lyricsyfi/lyricsyfi/Program.cs:line 9
```

This happens on both `dotnet 2.1.301` and `mono 5.10.1.47`.

**Comment by peacecwz** [comment]
Thanks for issue. I released 1.0.2 version. It's fixed

**Comment by Herbstein** [comment]
Works perfectly! I am wondering how I should setup authentication to the local app in my Spotify dashboard. Using my local IP obviously isn't portable at all, so which should I whitelist?

**Comment by Herbstein** [comment]
I figured out why I had issues! In my app I had to use `localhost:5000/` as the URI, but on the developer portal I had to input `localhost:5000`.
